export const GameEvent = {
    GAME_LOADING_ENDED:         "GAME_LOADING_ENDED",
    GAME_ON_SHOW:               "GAME_ON_SHOW",
    GAME_ON_HIDE:               "GAME_ON_HIDE",

    USER_LEVEL_CHANGED:         "USER_LEVEL_CHANGED",
    USER_GOLD_CHANGED:          "USER_GOLD_CHANGED",
    USER_STAR_CHANGED:          "USER_STAR_CHANGED",
    USER_ENERGY_CHANGED:        "USER_ENERGY_CHANGED",
   
    USER_TASK_CHANGED:          "USER_TASK_CHANGED",

    // 跨天事件
    SYSTEM_CROSS_DAY:           "SYSTEM_CROSS_DAY",
    // 整点报时
    SYSTEM_CROSS_HOUR:          "SYSTEM_CROSS_HOUR",
   
    GAMEWORLD_ENABLE_CHANGED:   "GAMEWORLD_ENABLE_CHANGED",

    USER_DAILY_ANIMAL_CHANGED:  "USER_DAILY_ANIMAL_CHANGED",
    USER_PLAY_COUNT_CHANGE:     "USER_PLAY_COUNT_CHANGE",
    
    GAME_START:                 "GAME_START",
    GAME_LEVEL_LOADED:          "GAME_LEVEL_LOADED",
    GAME_INIT_RESET_BLOCK:      "GAME_INIT_RESET_BLOCK",
    GAME_RESET_BLOCK:           "GAME_RESET_BLOCK",
    
    GAME_OVER:                  "GAME_OVER",
    GAME_LEVEL_BEFORE_LOAD:     "GAME_LEVEL_BEFORE_LOAD",
    GAME_LEVEL_START:           "GAME_LEVEL_START",
    GAME_LEVEL_OVER:            "GAME_LEVEL_OVER",
    GAME_NEXT_LEVEL:            "GAME_NEXT_LEVEL",
    GAME_LEVEL_SUCCESS:         "GAME_LEVEL_SUCCESS",

    GAME_MOVE_BLOCK_IN:         "GAME_MOVE_BLOCK_IN",
    GAME_MOVE_BLOCK_OUT:        "GAME_MOVE_BLOCK_OUT",
    GAME_MOVE_BLOCK_CANCLE:      "GAME_MOVE_BLOCK_CACLE",
    GAME_MOVE_BLOCK_PUTIN:      "GAME_MOVE_BLOCK_PUTIN",
    GAME_ENTER_BOMB_MODE:       "GAME_ENTER_BOMB_MODE",
    GAME_EXIT_BOMB_MODE:        "GAME_EXIT_BOMB_MODE",

    // 生成了特殊方块
    GAME_SPECIAL_BLOCK_SHOW:     "GAME_SPECIAL_BLOCK_SHOW",
    GAME_ORDER_COMPLETE:        "GAME_ORDER_COMPLETE",
    
    // 时间提醒
    GAME_TIMER_NOTICE:          "GAME_TIMER_NOTICE",
    // 复活
    GAME_RELIVE:                "GAME_RELIVE",
    GAME_ADD_TIME:              "GAME_ADD_TIME",
};